title: Welcome github webpage.
author: Chandrashekhar  Bharti
email: cbhartee11@gmail.com
theme:minima
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

# social links
twitter_username:www.twitter.com # DO NOT include the @ character, or else the build will fail!
github_username: https://github.com/Chandrashekhar-Bharti  # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
plugins_dir: [ DIR1,... ]

-p, --plugins DIR1[,DIR2,...]
layouts_dir: DIR

--layouts DIR
